### ISSUE TITLE
AWS S3 token expiration issue, should renew token

### ISSUE THREAD

**Issue by leonidd-hyuna** [thephpleague/flysystem-aws-s3-v3#249]
In long lasting scripts i'm getting `token expired error` 
as I understand there is should be posibility to check if token going to be expired or already expired then try to reconnect before throw exception
so after 1 hour processing it fails
something like this:
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message (truncated...)
 ExpiredToken (client): The provided token has expired. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Token-0>F......K</RequestId><HostId>XIN.......SOk=</HostId></Error> at /var/www/html/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195)

[stacktrace]
#0 /var/www/html/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\\Psr7\\Request), Object(Aws\\Command), Array)
#1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\\WrappedHttpHandler->Aws\\{closure}(Array)
#2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\\Promise\\Promise::callHandler(2, Array, NULL)
#3 /var/www/html/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}(Array)
#4 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\RejectedPromise::GuzzleHttp\\Promise\\{closure}()
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(158): GuzzleHttp\\Promise\\TaskQueue->run()
#6 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(183): GuzzleHttp\\Handler\\CurlMultiHandler->tick()
#7 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Handler\\CurlMultiHandler->execute(true)
#8 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#9 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#10 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#11 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#12 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#13 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#14 /var/www/html/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\\Promise\\Promise->wait()
#15 /var/www/html/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(711): Aws\\AwsClient->execute(Object(Aws\\Command))
#16 /var/www/html/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(237): League\\Flysystem\\AwsS3v3\\AwsS3Adapter->doesDirectoryExist('ingestion/raw-d...')
#17 /var/www/html/vendor/league/flysystem/src/Filesystem.php(57): League\\Flysystem\\AwsS3v3\\AwsS3Adapter->has('ingestion/raw-d...')
#18 /var/www/html/vendor/league/flysystem/src/Filesystem.php(388): League\\Flysystem\\Filesystem->has('ingestion/raw-d...')
#19 /var/www/html/vendor/league/flysystem/src/Filesystem.php(179): League\\Flysystem\\Filesystem->assertPresent('ingestion/raw-d...')
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(152): League\\Flysystem\\Filesystem->read('ingestion/raw-d...')
#21 /var/www/html/app/Ingestion/Vendors/Ebook/HCUSEbookVendor.php(55): Illuminate\\Filesystem\\FilesystemAdapter->get('ingestion/raw-d...')

**Comment by leonidd-hyuna** [comment]
Yeah, in fact it could be not your's issue because i figured out we are using `stsClient` to assume IAM role to s3Client
however when temporary token is dead your client still trying to get response and throws exception

or additionally should be another way to use stsClient with your library to it work properly 

```
Storage::extend('s3', function($app, $config = null) {
            try {
                $stsClient = new StsClient([
                    'profile' => 'default',
                    'region' => $config['region'],
                    'version' => '2011-06-15'
                ]);
                
                $stsClient->assumeRole([
                    'RoleArn' => $config['role_arn'],
                    'RoleSessionName' => $config['source_profile']
                ]);
                // output AssumedRole credentials, you can use these credentials
                // to initiate a new AWS Service client with the IAM Role's permissions

                $result = $stsClient->getSessionToken();
                $credentials = $stsClient->createCredentials($result);
                $s3Client = new S3Client([
                    'version'     => '2006-03-01',
                    'region'      => $config['region'],
                    'credentials' =>  $credentials
                ]);

                return new Filesystem(new S3Adapter($s3Client, $config['bucket']));
            } catch (AwsException $e) {
                // output error message if fails
                error_log($e->getMessage());
            }
        });
        ```

**Comment by leonidd-hyuna** [comment]
https://docs.aws.amazon.com/aws-sdk-php/v2/guide/credentials.html#providing-temporary-credentials-to-the-sdk

**Comment by xXLXx** [comment]
@leonidd-hyuna have you found a way around this one? It's a wierd issue I'm only having on laravel queue

**Comment by joselin-bizmatesph** [comment]
> @leonidd-hyuna have you found a way around this one? It's a wierd issue I'm only having on laravel queue

Have you already solved this issue? I am having the same issue

**Comment by xXLXx** [comment]
@joselin-bizmatesph I ended up extending `Illuminate\Filesystem\FilesystemManager`. And since the cause for the expired token in my case is the expiring tokens from AWS assume role, I just try to check on the expiry in the get function:

```
protected function get($name)
    {
        $disk = $this->disks[$name] ?? $this->resolve($name);

        if ($disk->expiresAt && $disk->expiresAt < time()) {
            $disk = $this->resolve($name);
        }

        return $disk;
    }
```

Is it the same case with yours? That you are using assume role mechanics as well ?

**Comment by joselin-bizmatesph** [comment]
@xXLXx 
Yes I am using assume role mechanics as well, everything is working but when the s3 is used in the Laravel queue then I end up receiving this error message

`The provided token has expired`

This is the implementation that I used

```
               Storage::extend('s3', function ($app, $config) {
                // Get Local IP address provided by ECS container metadata
                $domain = 'http://' . parse_url($config['metadata_container'], PHP_URL_HOST) . "/";
                $response = HttpRequest::get($domain . $config['metadata_credential_path']);
                unset($config['key']);
                unset($config['secret']);
                // Identify S3 endpoint
                $config['url'] = "https://"
                    . $config['bucket']
                    . ".s3."
                    . $config['region']
                    . "."
                    . $config['url'];
                $config['credentials'] = [
                    'key' => $response->AccessKeyId,
                    'secret' => $response->SecretAccessKey,
                    'token' => $response->Token
                ];
                $config['version'] = 'latest';
                $adapter = new AwsS3Adapter(
                    new S3Client(
                        $config
                    ),
                    $config['bucket']
                );

                return new FilesystemAdapter(
                    new Filesystem($adapter, $config),
                    $adapter,
                    $config
                );
            });
```

**Comment by xXLXx** [comment]
Ahh yeah @joselin-bizmatesph  I had the same implementation at first as well but realized due to FlySystem actually caching the storage on `->get()` call, even if you created a new instance of the `AwsS3Adapter` (now with renewed tokens), it will still return to you the old one. This is cached and stored in an array inside the class.

So first, I created my own service provider (just to make it clean). This is a replacement to the FlySystem provider you included under config/app.php


FilesystemServiceProvider.php
```php
<?php

namespace App\Providers;

use Illuminate\Filesystem\FilesystemServiceProvider as IlluminateFilesystemServiceProvider;
use App\Services\Filesystem\FilesystemManager;

class FilesystemServiceProvider extends IlluminateFilesystemServiceProvider
{
    /**
     * Register the filesystem manager.
     *
     * @return void
     */
    protected function registerManager()
    {
        $this->app->singleton('filesystem', function ($app) {
            return new FilesystemManager($app);
        });
    }
}

```

This is where the actual logic is, this is like how you did your part of the code. I just did it this way due to the `get` method. Also notice how expiresAt is being passed around until `FilesystemAdapter` creation, this is due to we wanted to check the `->expiresAt` which is stored under `$this->disks` -- The caching mechanism I just mentioned

FilesystemManager.php
```php
<?php

namespace App\Services\Filesystem;

use Aws\S3\S3Client;
use Aws\Sts\StsClient;
use Illuminate\Filesystem\FilesystemManager as IlluminateFilesystemManager;
use League\Flysystem\AwsS3v3\AwsS3Adapter as S3Adapter;
use League\Flysystem\FilesystemInterface;

class FilesystemManager extends IlluminateFilesystemManager
{
    /**
     * Attempt to get the disk from the local cache.
     *
     * @param  string  $name
     * @return \Illuminate\Contracts\Filesystem\Filesystem
     */
    protected function get($name)
    {
        $disk = $this->disks[$name] ?? $this->resolve($name);

        if ($disk->expiresAt && $disk->expiresAt < time()) {
            $disk = $this->resolve($name);
        }

        return $disk;
    }

    /**
     * Create an instance of the Amazon S3 driver.
     *
     * @param  array  $config
     * @return \Illuminate\Contracts\Filesystem\Cloud
     */
    public function createS3Driver(array $config)
    {
        $s3Config = $this->formatS3Config($config);

        $root = $s3Config['root'] ?? null;

        $options = $config['options'] ?? [];

        $streamReads = $config['stream_reads'] ?? false;

        // $s3Config['credentials'] = static::credentialsProvider($s3Config);

        if (isset($s3Config['assumeRole'])) {
            if ($s3Config['assumeRole']['arn'] && $s3Config['assumeRole']['sessionName']) {
                $stsClient = new StsClient($s3Config);

                $result = $stsClient->AssumeRole([
                    'RoleArn' => $s3Config['assumeRole']['arn'],
                    'RoleSessionName' => $s3Config['assumeRole']['sessionName'],
                ]);

                $s3Config['credentials'] = [
                    'secret'    => $result['Credentials']['SecretAccessKey'],
                    'key'       => $result['Credentials']['AccessKeyId'],
                    'token'     => $result['Credentials']['SessionToken'],
                    'expires'   => $result['Credentials']['Expiration']
                ];
            }
        }

        $client = new S3Client($s3Config);

        return $this->adapt($this->createFlysystem(
            new S3Adapter($client, $s3Config['bucket'], $root, $options, $streamReads), $config
        ), $s3Config['credentials'] ? strtotime($s3Config['credentials']['expires']) : null);
    }

    /**
     * Adapt the filesystem implementation.
     *
     * @param  \League\Flysystem\FilesystemInterface  $filesystem
     * @param int $expiresAt
     * @return \App\Services\Filesystem\FilesystemAdapter
     */
    protected function adapt(FilesystemInterface $filesystem, int $expiresAt = null)
    {
        return new FilesystemAdapter($filesystem, $expiresAt);
    }
}

```

This file is more of just a requirement since we need to access `->expiresAt`, that's why I extended this as well

FilesystemAdapter.php
```php
<?php

namespace App\Services\Filesystem;

use Illuminate\Support\Str;
use Illuminate\Filesystem\FilesystemAdapter as IlluminateFilesystemAdapter;
use League\Flysystem\FilesystemInterface;

class FilesystemAdapter extends IlluminateFilesystemAdapter {
    public $expiresAt = null;

    /**
     * Create a new filesystem adapter instance.
     *
     * @param  \League\Flysystem\FilesystemInterface  $driver
     * @param int $expiresAt
     * @return void
     */
    public function __construct(FilesystemInterface $driver, int $expiresAt = null)
    {
        parent::__construct($driver);

        $this->expiresAt = $expiresAt;
    }
}
```

**Comment by joselin-bizmatesph** [comment]
@xXLXx 
Thank you very much, This solved my problem.

**Comment by leonidd-hyuna** [comment]
@xXLXx Hey! Thanks a lot for solving it looks really good!
However i found your answer only now :)) To solve this issue i'm using "queue listen" with timout parameter instead of "queue work" this help to recreate connection with each request and also i asked my DevOps to make session time as much as possible, it's about 1 day maybe.

**Comment by xXLXx** [comment]
@leonidd-hyuna  Ahh I see yeah I found that solution as well before but though that isn't `queue:listen` only used so that everytime you update the code, the queue instance / the cron is actually reset. And that's why you are now able to get the new creds?

I was thinking at that time that even when this is true, it still won't refresh regularly, unless you update the code regularly.

**Comment by leonidd-hyuna** [comment]
@xXLXx did you update your laravel to v9 successfully?
Yesterday i've updated to L9 with all the libraries and found that have now another issue with flysystem and AWS FilesListing request
 issue related to "Extra slash" added by prefixer :(
 
when i'm trying to get list of files with prefix that is not ending with '/' but is part of files naming i got empty list of files because of prefixer adding slash at the end of prefix
$feedList = $storage->listContents($this->feedLocation . $this->feedNamePrefix);

Why it is trying to trim and write back this slash at all ?!
my path is looks like "media/group/fileprefix_"
and for example it should return files like "media/group/fileprefix_20220618.csv" in native AWS SDK it work this way
![image](https://user-images.githubusercontent.com/14912939/186198393-dad0f0a7-3df8-43ba-ab38-5b3daed9cb74.png)

**Comment by xXLXx** [comment]
Ohhh @leonidd-hyuna  I haven't tried this or myself. But yeah I agree looks like a wierd change. The other versions do a `'Prefix' => ltrim($prefix, '/')` which makes more sense than this one

**Comment by FateevDev** [comment]
S3 credentials can receive a callable as a value. So, in your case, you can use \Aws\Credentials\CredentialProvider as credentials:

```
Storage::extend('s3-custom', function (Application $app, array $config) {
            $cache = $app->make(\Psr\SimpleCache\CacheInterface::class);

            $config['credentials'] = CredentialProvider::cache(new AssumeRoleCredentialProvider(), new Psr16CacheAdapter($cache));

            return (new FilesystemManager($app))->createS3Driver($config);
        });
```

Thus, when you use this driver in a worker (long-lasting scripts), every time it needs credentials, it will call the cached credentials from CredentialProvider. 
When the cache expires, it will use AssumeRoleCredentialProvider to get new credentials.

[More](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html) information about credentials provider
